---
#
# Tasks and roles for all hosts
#
- hosts: HAL9000
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - always
        - port

- hosts: all
  become: yes

  roles:
    #
    # Basics
    #
    - role: system
      tags:
        - system

    - role: neovim
      tags:
        - neovim

    - role: geerlingguy.security
      tags:
        - security

    - role: geerlingguy.docker
      tags:
        - docker

    - role: chriswayg.msmtp-mailer
      tags:
        - msmtp

    - role: containers
      tags:
        - containers

    - role: certbot
      tags:
        - certbot

    - name: nginx
      tags:
        - nginx
