#
# Misc
#
hostname: "{{ inventory_hostname }}"

timezone: Europe/Amsterdam

ntp_timezone: "{{ timezone }}"

locale: en_US.UTF-8

keyboard_layout: us

dotfiles_repo: https://github.com/notthebee/dotfiles

shell: /usr/bin/fish

#
# Docker apps
#
docker_compose_dir: /opt/docker/compose
docker_data_dir: /opt/docker/data

#
# Packages
#
extra_packages:
  - fish
  - htop
  - stow
  - git
  - screen
  - neofetch
  - smartmontools
  - neovim
  - radeontop
  - tmux
  - rsync
  - lm-sensors
  - powertop

extra_snap_packages:
  - ngrok
  - speedtest

#
# Email credentials (for notifications)
#
email_login: "{{ email }}"
email_smtp_port: 465
email_smtp_port_startls: 587

# MSMTP
msmtp_accounts:
  - account: mailbox
    host: "{{ email_smtp_host }}"
    port: "{{ email_smtp_port_startls }}"
    auth: "on"
    from: "{{ email }}"
    user: "{{ email }}"
    password: "{{ email_password }}"

msmtp_default_account: "mailbox"

msmtp_alias_default: "{{ email }}"

#
# SSH (geerlingguy.security)
#
security_autoupdate_reboot: true

security_autoupdate_mail_to: "{{ email }}"

security_autoupdate_reboot_time: "03:00"

security_autoupdate_mail_on_error: true

update_utility: dnf-automatic

update_service: dnf-automatic-install.timer

update_conf_path: /etc/dnf/automatic.conf
