---
- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}/watchtower"

- name: Copy the watchtower compose file
  template:
    src: templates/watchtower-compose.yml
    dest: "{{ docker_compose_dir }}/watchtower/compose.yml"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}/watchtower"
